#' @title MGYS00000974 data
#'
#' @description A dataframe containing the accession, sample-name, sample-desc and sample metadata from MGYS00000974.
#' This dataset was generated by the j craig venster instute \link{https://www.ebi.ac.uk/ena/data/view/PRJEB8968}
#'
#' @format A dataframe with 17 columns and 277 rows:
#' \describe{
#' \item{accession}{The sample accession}
#' \item{sample-name}{The name of the sample, including filter size}
#' \item{sample-desc}{Description of sample information}
#' \item{biome}{Describes specific environment of sample}
#' \item{X}{Longtitude}
#' \item{Y}{Latitude}
#' \item{silicate}{Silicate concentration in umol/L}
#' \item{temperature}{Temperature in degrees Celsius}
#' \item{depth}{Depth in meters}
#' \item{region}{Type of location of sample}
#' \item{collection_date}{Sampling date}
#' \item{environment_biome}{General biome of sample}
#' \item{environment_feature}{Biome feature of sample}
#' \item{environmental_package}{MIxS package applied}
#' \item{chlorophyll}{Chlorophyll concentration in mg/m3}
#' \item{dissolved_oxygen}{Dissolved oxygen concentration in mg/L}
#' \item{nitrate}{Nitrate concentration in umol/L}
#' \item{phosphate}{Phosphate concentration in umol/L}
#' \item{salinity}{Salinity in ppt}
#' \item{NCBI_sample_classification}{ID for NCBI class}
#' \item{instrument_model}{Sequencing device used}
#' \item{ENA_checklist}{Checklist used for ENA}
#' }

"MGYS00000974"
